# Generated by Django 5.0.3 on 2024-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_equipment_def_tot_alter_equipment_reload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='dmg_base',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='dmg_base',
            field=models.CharField(max_length=5),
        ),
    ]
