# Generated by Django 5.0.2 on 2024-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('', ''), ('drs', 'CO DRS'), ('compagnon', 'CO Compagnon'), ('5E', 'D&D 5E'), ('homebrew', 'Règle Maison')], max_length=100)),
                ('spell', models.BooleanField(default=False)),
                ('limited', models.BooleanField(default=False)),
            ],
        ),
    ]
