# Generated by Django 5.0.2 on 2024-02-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='encounter',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('', ''), ('drs', 'CO DRS'), ('compagnon', 'CO Compagnon'), ('5E', 'D&D 5E'), ('homebrew', 'Règle Maison')], max_length=100)),
                ('prestige', models.BooleanField(default=False)),
                ('racial', models.BooleanField(default=False)),
                ('encounter', models.BooleanField(default=False)),
                ('capacities', models.ManyToManyField(to='rules.capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('', ''), ('drs', 'CO DRS'), ('compagnon', 'CO Compagnon'), ('5E', 'D&D 5E'), ('homebrew', 'Règle Maison')], max_length=100)),
                ('dv', models.CharField(max_length=4)),
                ('spellcasting', models.CharField(max_length=3)),
                ('mpfactor', models.PositiveSmallIntegerField(default=0)),
                ('prestige', models.BooleanField(default=False)),
                ('paths', models.ManyToManyField(to='rules.path')),
            ],
        ),
    ]
