# Generated by Django 5.0.2 on 2024-02-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_capacity_encounter_path_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('', ''), ('drs', 'CO DRS'), ('compagnon', 'CO Compagnon'), ('5E', 'D&D 5E'), ('homebrew', 'Règle Maison')], max_length=100)),
                ('STR', models.SmallIntegerField(default=0)),
                ('DEX', models.SmallIntegerField(default=0)),
                ('CON', models.SmallIntegerField(default=0)),
                ('INT', models.SmallIntegerField(default=0)),
                ('WIS', models.SmallIntegerField(default=0)),
                ('CHA', models.SmallIntegerField(default=0)),
                ('capacities', models.ManyToManyField(to='rules.capacity')),
                ('paths', models.ManyToManyField(to='rules.path')),
            ],
        ),
    ]
