# Generated by Django 5.0.2 on 2024-03-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name_plural': 'Capacities'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
    ]
