# Generated by Django 5.0.2 on 2024-03-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_alter_capacity_options_alter_species_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
