# Generated by Django 5.0.3 on 2024-04-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_alter_species_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='source',
        ),
        migrations.RemoveField(
            model_name='path',
            name='source',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='source',
        ),
        migrations.RemoveField(
            model_name='species',
            name='source',
        ),
    ]
