# Generated by Django 5.0.3 on 2024-04-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_capacity_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paths', to='rules.source'),
        ),
        migrations.AddField(
            model_name='profile',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='rules.source'),
        ),
        migrations.AddField(
            model_name='species',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='species', to='rules.source'),
        ),
    ]
