# Generated by Django 5.0.3 on 2024-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_equipment_critrange_alter_equipment_trait_and_more'),
        ('rules', '0010_itemtrait_alter_source_options_alter_species_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='items.item'),
        ),
    ]
