# Generated by Django 5.0.4 on 2024-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_profile_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=models.SlugField(unique=False),
        ),
    ]
