# Generated by Django 5.0.4 on 2024-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0015_alter_capacity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='path',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
