# Generated by Django 5.0.4 on 2024-04-22 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_alter_capacity_description_alter_path_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='capacities',
        ),
        migrations.CreateModel(
            name='PathCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.capacity')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.path')),
            ],
            options={
                'unique_together': {('path', 'capacity')},
            },
        ),
        migrations.AddField(
            model_name='path',
            name='capacity',
            field=models.ManyToManyField(through='rules.PathCapacity', to='rules.capacity'),
        ),
    ]
