# Generated by Django 5.0.4 on 2024-04-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0017_remove_path_capacities_pathcapacity_path_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='capacity',
            new_name='capacities',
        ),
    ]
