# Generated by Django 5.0.2 on 2024-03-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('rules', '0004_alter_capacity_options_alter_species_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cha',
            name='id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.RemoveField(
            model_name='con',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dex',
            name='id',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='int',
            name='id',
        ),
        migrations.RemoveField(
            model_name='magic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='melee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ranged',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wis',
            name='id',
        ),
        migrations.AddField(
            model_name='cha',
            name='statistic_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.statistic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='actor_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='rules.species'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='con',
            name='statistic_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.statistic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dex',
            name='statistic_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.statistic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encounter',
            name='actor_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='int',
            name='statistic_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.statistic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magic',
            name='attack_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.attack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='melee',
            name='attack_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.attack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npc',
            name='actor_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranged',
            name='attack_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.attack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wis',
            name='statistic_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.statistic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='actor',
            name='size',
            field=models.CharField(choices=[('tiny', 'Minuscule'), ('really_small', 'Très petit'), ('small', 'Petit'), ('medium', 'Moyen'), ('tall', 'Grand'), ('huge', 'Énorme'), ('colossal', 'Colossale')], max_length=100),
        ),
    ]
