# Generated by Django 5.0.2 on 2024-03-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_remove_cha_id_remove_character_id_remove_con_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='actors.languages'),
        ),
    ]
