# Generated by Django 5.0.2 on 2024-03-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_character_eyes_alter_character_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(blank=True, to='actors.languages'),
        ),
    ]
