# Generated by Django 5.0.2 on 2024-03-15 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_alter_character_languages'),
        ('rules', '0004_alter_capacity_options_alter_species_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LP',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.attribute')),
                ('label', models.CharField(default='Points de Chance', editable=False, max_length=100)),
                ('abbrev', models.CharField(default='PC', editable=False, max_length=100)),
            ],
            bases=('actors.attribute',),
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='actor',
        ),
        migrations.AddField(
            model_name='character',
            name='CHA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.cha'),
        ),
        migrations.AddField(
            model_name='character',
            name='CON',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.con'),
        ),
        migrations.AddField(
            model_name='character',
            name='DEF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.def'),
        ),
        migrations.AddField(
            model_name='character',
            name='DEX',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.dex'),
        ),
        migrations.AddField(
            model_name='character',
            name='HP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.hp'),
        ),
        migrations.AddField(
            model_name='character',
            name='INT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.int'),
        ),
        migrations.AddField(
            model_name='character',
            name='MP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.mp'),
        ),
        migrations.AddField(
            model_name='character',
            name='RP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.rp'),
        ),
        migrations.AddField(
            model_name='character',
            name='STR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.str'),
        ),
        migrations.AddField(
            model_name='character',
            name='WIS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.wis'),
        ),
        migrations.AddField(
            model_name='character',
            name='init',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.init'),
        ),
        migrations.AddField(
            model_name='character',
            name='magic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.magic'),
        ),
        migrations.AddField(
            model_name='character',
            name='melee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.melee'),
        ),
        migrations.AddField(
            model_name='character',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='rules.profile'),
        ),
        migrations.AddField(
            model_name='character',
            name='ranged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.ranged'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='CHA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='actors.cha'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='CON',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='actors.con'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='DEX',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='actors.dex'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='INT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='actors.int'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='STR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='actors.str'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='WIS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='actors.wis'),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='rules.species'),
        ),
        migrations.AddField(
            model_name='character',
            name='LP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='actors.lp'),
        ),
    ]
