# Generated by Django 5.0.4 on 2024-04-17 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0010_remove_character_owner_actor_owner'),
        ('rules', '0016_alter_capacity_description_alter_path_img_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='age',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='eyes',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='hair',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='height',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='weight',
        ),
        migrations.AddField(
            model_name='actor',
            name='languages',
            field=models.ManyToManyField(blank=True, to='actors.languages'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='HP_max',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='HP_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='RD_temp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='RD_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='access',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='boss',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Remarquable'), ('2', 'Supérieur'), ('3', 'Majeur'), ('4', 'Exceptionnel'), ('5', 'Légendaire')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='capacity',
            field=models.ManyToManyField(blank=True, related_name='encounters', to='rules.capacity'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='def_temp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='def_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='init_temp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='init_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='magic_base',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='encounter',
            name='magic_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='magic_dm_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='magic_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='magic_malus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='magic_mod',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='magic_stat',
            field=models.CharField(choices=[('STR', 'Force'), ('DEX', 'Dextérité'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Sagesse'), ('CHA', 'Charisme')], default='INT', max_length=3),
        ),
        migrations.AddField(
            model_name='encounter',
            name='melee_base',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='encounter',
            name='melee_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='melee_dm_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='melee_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='melee_malus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='melee_mod',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='melee_stat',
            field=models.CharField(choices=[('STR', 'Force'), ('DEX', 'Dextérité'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Sagesse'), ('CHA', 'Charisme')], default='STR', max_length=3),
        ),
        migrations.AddField(
            model_name='encounter',
            name='path',
            field=models.ManyToManyField(blank=True, related_name='encounters', to='rules.path'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ranged_base',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ranged_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ranged_dm_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ranged_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ranged_malus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ranged_mod',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ranged_stat',
            field=models.CharField(choices=[('STR', 'Force'), ('DEX', 'Dextérité'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Sagesse'), ('CHA', 'Charisme')], default='DEX', max_length=3),
        ),
        migrations.AddField(
            model_name='npc',
            name='access',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='archetype',
            field=models.CharField(blank=True, choices=[('', ''), ('standard', 'Standard'), ('fast', 'Rapide'), ('powerful', 'Puissant'), ('lesser', 'Inférieur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('living', 'Vivante'), ('humanoid', 'Humanoïde'), ('plant', 'Végétale'), ('unliving', 'Non-vivante')], max_length=100, null=True),
        ),
    ]
