# Generated by Django 5.0.4 on 2024-04-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0012_npc_hp_base_npc_hp_bonus_npc_hp_max_npc_hp_value_and_more'),
        ('rules', '0016_alter_capacity_description_alter_path_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='languages',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='actor',
            name='size',
            field=models.CharField(choices=[('tiny', 'Minuscule'), ('really_small', 'Très petit'), ('small', 'Petit'), ('medium', 'Moyen'), ('tall', 'Grand'), ('huge', 'Énorme'), ('colossal', 'Colossale')], default='MEDIUM', max_length=100),
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('spell', models.BooleanField(default=False)),
                ('limited', models.BooleanField(default=False)),
                ('encounter', models.BooleanField(default=False)),
                ('learned', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='actors.actor')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowned_capacities', to='rules.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
