# Generated by Django 5.0.4 on 2024-04-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0014_alter_capacity_slug_alter_character_profile_and_more'),
        ('rules', '0016_alter_capacity_description_alter_path_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='known_capacities', to='rules.path'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='known_capacities', to='rules.source'),
        ),
    ]
