# Generated by Django 5.0.4 on 2024-04-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0015_capacity_path_alter_capacity_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
