# Generated by Django 5.0.4 on 2024-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0016_capacity_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='capacity_point',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
